name: Build and Deploy Alpine Repository

on:
  push:
    branches:
      - alpine
  workflow_dispatch:

jobs:
  build-alpine-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK Packages inside Alpine Container
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace alpine:latest sh build-alpine.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
